import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";

const preventDefault = (f) => (e) => {
  e.preventDefault();
  f(e);
};

export default function Contactus({ action = "/searchpage" }) {
  const router = useRouter();
  const [query, setQuery] = useState("");

  const handleParam = (setValue) => (e) => setValue(e.target.value);

  const handleSubmit = preventDefault(() => {
    router.push({
      pathname: action,
      query: { q: query },
    });
  });

  return (
    <div>
      <Head>
        <title>Contact - Basic WP Setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container my-2">
        <Navbar />

        <h1>Contact Page</h1>

		<form onSubmit={handleSubmit}>
        <input
          type="text"
          name="q"
          value={query}
          onChange={handleParam(setQuery)}
          placeholder="Search"
          aria-label="Search"
        />
        <button type="submit">Submit</button>
      </form>
      </div>
    </div>
  );
};
