import React from 'react'
import Head from "next/head";
import Link from "next/link";
import Navbar from "../components/Navbar";

export default function Home({pagesdata}) {

  // HOMEPAGE ID
  const homePageID = 5;

  return (
    <>
      <Head>
        <title>Basic WP Setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container my-2">
        <Navbar />

        {pagesdata.filter(post => post.id == homePageID).map(post => (
            <div key={post.id} className="row">
                <div className="col-md-6">
                    <h4>{post.acf.banner_title}</h4>
                    <div dangerouslySetInnerHTML={{__html: `${post.acf.banner_body}`}}></div>
                </div>
                <div className="col-md-6">
                    <img src={post.acf.banner_image.url} alt={post.acf.banner_title} />
                </div>
            </div>
        ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch('https://gridspective.com/Website-Demos/wp-react-next/wp-json/wp/v2/pages?acf_format=standard')
  const pagesdata = await res.json();
  return {
    props: {
      pagesdata,
    },
    revalidate: 10,
  }
}