import {useState} from 'react'
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";

export default function Searchpage({searchPageData}) {

    const router = useRouter()
    const routerlink = router.query;
    const routerslug = routerlink.q;
    console.log(routerslug);
    
    //const {routerslug} = router.query;
    //console.log(`${contactus.query}`)
    
  return (
    <>
    <Head>
      <title>Showing results for: {routerslug} - Basic WP Setup</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container my-2">
        <Navbar />

        <h1>Showing results for: {routerslug}</h1>

        <div className='my-5 row'>
            {searchPageData.filter(contpost => contpost.content.rendered.toLowerCase().includes(routerslug)).map(filteredPost => (
                <div key={filteredPost.id} className='col-md-4'>
                  <div className="searchblock mb-5">
                      <h4>{filteredPost.title.rendered}</h4>
                      <div dangerouslySetInnerHTML={{__html: `${filteredPost.excerpt.rendered}`.substring(0, 200) + `...`}}></div>
                      {/* <Link href={`/posts/${filteredPost.slug}`}></Link> */}
                      <Link href={filteredPost.slug}>
                        <a className='btn btn-primary'>Know more</a>
                      </Link>
                  </div>
                </div>
            ))}
        </div>
    </div>
  </>
  )
}

export async function getStaticProps() {
    // const res = await fetch('https://gridspective.com/Website-Demos/wp-react-next/wp-json/wp/v2/pages?acf_format=standard')
    // const res = await fetch('https://gridspective.com/Website-Demos/wp-react-next/wp-json/wp/v2/pages')
    const res = await fetch('https://redbytes.co.uk/wp-json/wp/v2/posts')
    const searchPageData = await res.json();
    return {
      props: {
        searchPageData,
      },
      revalidate: 10,
    }
  }